export const TYPES = {
  AwsHttpClientService: Symbol.for('AwsHttpClientService'),
  DateAndTimeService: Symbol.for('DateAndTimeService'),
  EcsTransformService: Symbol.for('EcsTransformService'),
  GeoIpService: Symbol.for('GeoIpService'),
  KinesisStreamService: Symbol.for('KinesisStreamService'),
  KinesisStreamRecordMapperService: Symbol.for('KinesisStreamRecordMapperService'),
  LoggerService: Symbol.for('LoggerService'),
  MaxmindAsnLookupService: Symbol.for('MaxmindAsnLookupService'),
  MaxmindCityLookupService: Symbol.for('MaxmindCityLookupService'),
  OpenSearchService: Symbol.for('OpenSearchService'),
  Parser: Symbol.for('Parser'),
  RandomizerService: Symbol.for('RandomizerService'),
  SubsetService: Symbol.for('SubsetService'),
};
