export const TYPES = {
  AwsHttpClientService: Symbol.for('AwsHttpClientService'),
  BatchSummaryService: Symbol.for('BatchSummaryService'),
  DateAndTimeService: Symbol.for('DateAndTimeService'),
  DeadLetterQueueService: Symbol.for('DeadLetterQueueService'),
  EcsTransformService: Symbol.for('EcsTransformService'),
  FieldExtractorService: Symbol.for('FieldExtractorService'),
  GeoIpService: Symbol.for('GeoIpService'),
  KinesisStreamService: Symbol.for('KinesisStreamService'),
  KinesisStreamWrapperService: Symbol.for('KinesisStreamWrapperService'),
  KinesisStreamRecordMapperService: Symbol.for('KinesisStreamRecordMapperService'),
  LoggerService: Symbol.for('LoggerService'),
  MaxmindAsnLookupService: Symbol.for('MaxmindAsnLookupService'),
  MaxmindCityLookupService: Symbol.for('MaxmindCityLookupService'),
  OpenSearchService: Symbol.for('OpenSearchService'),
  PreInitParser: Symbol.for('PreInitParser'),
  InitParser: Symbol.for('InitParser'),
  PreParser: Symbol.for('PreParser'),
  Parser: Symbol.for('Parser'),
  PostParser: Symbol.for('PostParser'),
  FinalizeParser: Symbol.for('FinalizeParser'),
  SubsetService: Symbol.for('SubsetService'),
  RegexService: Symbol.for('RegexService'),
};
