setup.kibana:
  host: "${KIBANA_URL}"
  protocol: "https"
  username: "${ELASTICSEARCH_USERNAME}"
  password: "${ELASTICSEARCH_PASSWORD}"

setup.kibana.ssl.enabled: true

setup.ilm.enabled: false
setup.ilm.rollover_alias: "logs-access-%{[agent.version]}"
setup.ilm.policy_name: "logs-access"
setup.template.name: "logs-access"
setup.template.pattern: "logs-access-*"

setup.dashboards.enabled: false
setup.dashboards.index: "logs-access-*"

#logging.level: "debug"
logging.metrics.enabled: false
monitoring.enabled: false

filebeat.modules:
- module: apache
  access:
    enabled: true
    var.paths: ["/sw_ux/httpd01/logs/*-access*.log*"]
    input:
      close_eof: true
  error:
    enabled: false
    var.paths: ["/sw_ux/httpd01/logs/*-error*.log*"]
    input:
      close_eof: true

output.elasticsearch:
  bulk_max_size: 3200
  worker: 3
  username: "${ELASTICSEARCH_USERNAME}"
  password: "${ELASTICSEARCH_PASSWORD}"
  hosts: ["${ELASTICSEARCH_URL}"]
  index: "logs-access-%{[agent.version]}-%{+yyyy.MM.dd}"
  ssl.verification_mode: none
  ssl.certificate_authorities:
    - ~/certs/elasticsearch.pem