name: APM Deploy to Production

on:
  workflow_dispatch:
    branches: [main]

env:
  TF_VERSION: 0.15.4
  TG_VERSION: 0.37.1

jobs:
  buildLambda:
    name: Build Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
        working-directory: ./event-stream-processing
      - run: npm run pack
        working-directory: ./event-stream-processing
      - uses: actions/upload-artifact@v3
        with:
          name: event-stream-processing
          path: event-stream-processing/event-stream-processing.zip
          retention-days: 1
  buildWorkflow:
    name: Build Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
        working-directory: ./workflow-cli
      - run: npm run pack
        working-directory: ./workflow-cli
      - uses: actions/upload-artifact@v3
        with:
          name: workflow-cli
          path: workflow-cli/workflow-cli.zip
          retention-days: 1

  plan:
    name: Terraform Plan
    needs: [buildLambda]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      # Install/Setup terraform CLI
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TFC_TEAM_TOKEN }}
      # Install/Setup terragrunt CLI
      - uses: peter-murray/terragrunt-github-action@v1.0.0
        with:
          terragrunt_version: ${{ env.TG_VERSION }}
      - uses: actions/download-artifact@v3
        with:
          name: event-stream-processing
          path: ./terraform
      # Create tfvars file as an alternative to setting TF_VAR environment variable for Terraform Cloud
      # https://github.com/hashicorp/setup-terraform/pull/79
      - name: Setup Terraform variable for agent monitor destination url
        working-directory: ./terraform
        id: vars
        run: |-
          cat > monitors.auto.tfvars <<EOF
          agent_monitor_webhook_url = "${{ secrets.AGENT_MONITOR_WEBHOOK_URL }}"
          EOF
      - name: Terraform Plan - Review before apply
        working-directory: terragrunt/prod
        env:
          app_image: ${{ env.IMAGE_ID }}:${{ github.event.workflow_run.head_branch}}
        run: terragrunt run-all plan --terragrunt-non-interactive
  apply:
    name: Terraform Apply
    needs: [plan, buildWorkflow]
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      # Install/Setup terraform CLI
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TFC_TEAM_TOKEN }}
      # Install/Setup terragrunt CLI
      - uses: peter-murray/terragrunt-github-action@v1.0.0
        with:
          terragrunt_version: ${{ env.TG_VERSION }}
      - uses: actions/download-artifact@v3
        with:
          name: event-stream-processing
          path: ./terraform
      - uses: actions/download-artifact@v3
        with:
          name: workflow-cli
          path: ./terraform
      - name: Unzip Cli
        working-directory: terraform
        run: unzip -qq workflow-cli.zip -d ./workflow-cli
      # Create tfvars file as an alternative to setting TF_VAR environment variable for Terraform Cloud
      # https://github.com/hashicorp/setup-terraform/pull/79
      - name: Setup Terraform variable for agent monitor destination url
        working-directory: ./terraform
        id: vars
        run: |-
          cat > monitors.auto.tfvars <<EOF
          agent_monitor_webhook_url = "${{ secrets.AGENT_MONITOR_WEBHOOK_URL }}"
          EOF
      - name: Terraform Apply
        working-directory: terragrunt/prod
        env:
          app_image: ${{ env.IMAGE_ID }}:${{ github.event.workflow_run.head_branch}}
        run: terragrunt run-all apply --terragrunt-non-interactive
