name: APM Removal for Development

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-workflow:
    name: Remove APM
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}

      - name: SAM delete
        run: |
          sam delete \
            --stack-name nr-apm-stack \
            --no-prompts
